### ISSUE TITLE
Question about old styles...

### ISSUE THREAD

**Issue by adlai** [michal-bures/konkr_web#9]
Am I optimistic, to think that the inclusion of [these old styles](https://github.com/michal-bures/konkr_web/blob/dc04ae9/_sass/_syntax-highlighting.scss) means you will be posting code samples in the news items?

**Comment by michal-bures** [comment]
Oh, took me a while to notice this post 🙂. Yes, you are being optimistic, these just came by default with the jekyll template I guess. If I ever get around to post some more technical blog posts, I will link to them for sure, but they will probably go to a different site. Or I might create a separate category for them here. But regular konkr updates are ment for the general playerbase, which I don't want to bore with programming topics 🙂.
